#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DLL_DIR="$SCRIPT_DIR/dll"
SRC_DIR="$SCRIPT_DIR/src"

# ============================================================
# 1. Find the EPBot DLL (newest EPBot*.dll in dll/)
# ============================================================
DLL_PATH=$(ls -t "$DLL_DIR"/EPBot*.dll 2>/dev/null | head -1)
if [ -z "$DLL_PATH" ]; then
    echo "ERROR: No EPBot*.dll found in $DLL_DIR"
    exit 1
fi
DLL_NAME=$(basename "$DLL_PATH")
echo "Using DLL: $DLL_NAME"

# ============================================================
# 2. Detect namespace from the DLL using .NET reflection
# ============================================================
DETECT_DIR=$(mktemp -d)
cat > "$DETECT_DIR/Program.cs" << 'CSEOF'
using System;
using System.Linq;
using System.Reflection;
var asm = Assembly.LoadFrom(Environment.GetCommandLineArgs()[1]);
var ns = asm.GetExportedTypes().FirstOrDefault()?.Namespace ?? "EPBot";
Console.Write(ns);
CSEOF
cat > "$DETECT_DIR/detect.csproj" << 'CSEOF'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
</Project>
CSEOF

echo "Detecting namespace..."
NAMESPACE=$(cd "$DETECT_DIR" && dotnet run -- "$DLL_PATH" 2>/dev/null)
rm -rf "$DETECT_DIR"
echo "Detected namespace: $NAMESPACE"

# ============================================================
# 3. Generate GlobalUsings.g.cs with namespace alias
# ============================================================
cat > "$SRC_DIR/GlobalUsings.g.cs" << USEOF
// Auto-generated by build.sh — do not edit manually
global using EPBot = ${NAMESPACE}.EPBot;
USEOF
echo "Generated GlobalUsings.g.cs: EPBot = ${NAMESPACE}.EPBot"

# ============================================================
# 4. Update csproj to reference the correct DLL and namespace
# ============================================================
# Update HintPath to point to the actual DLL
sed -i '' "s|<HintPath>.*</HintPath>|<HintPath>../dll/${DLL_NAME}</HintPath>|" "$SRC_DIR/epbot-native.csproj"
# Update RootNamespace (if present) or add it
if grep -q '<RootNamespace>' "$SRC_DIR/epbot-native.csproj"; then
    sed -i '' "s|<RootNamespace>.*</RootNamespace>|<RootNamespace>${NAMESPACE}</RootNamespace>|" "$SRC_DIR/epbot-native.csproj"
else
    sed -i '' "s|<Nullable>enable</Nullable>|<Nullable>enable</Nullable>\n    <RootNamespace>${NAMESPACE}</RootNamespace>|" "$SRC_DIR/epbot-native.csproj"
fi

# ============================================================
# 5. Build with NativeAOT
# ============================================================
RID="${1:-}"
if [ -z "$RID" ]; then
    # Auto-detect RID
    case "$(uname -s)-$(uname -m)" in
        Darwin-arm64) RID="osx-arm64" ;;
        Darwin-x86_64) RID="osx-x64" ;;
        Linux-x86_64) RID="linux-x64" ;;
        Linux-aarch64) RID="linux-arm64" ;;
        MINGW*|MSYS*|CYGWIN*) RID="win-x64" ;;
        *) echo "ERROR: Cannot detect RID for $(uname -s)-$(uname -m)"; exit 1 ;;
    esac
fi
echo "Building for RID: $RID"

dotnet publish "$SRC_DIR/epbot-native.csproj" -r "$RID" -c Release

# ============================================================
# 6. Report output
# ============================================================
PUBLISH_DIR="$SRC_DIR/bin/Release/net10.0/$RID/publish"
echo ""
echo "Build complete. Output:"
ls -lh "$PUBLISH_DIR"/EPBotWrapper* 2>/dev/null || ls -lh "$PUBLISH_DIR"/libEPBotWrapper* 2>/dev/null || echo "Check $PUBLISH_DIR"
